- name: fetch repo
  hg: repo={{ app_repo }} dest={{ app_path }}

- name: copy nginx conf
  become: yes
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/{{ app_name }}

- name: enable nginx conf
  become: yes
  file: src=/etc/nginx/sites-available/{{ app_name }} dest=/etc/nginx/sites-enabled/{{ app_name }} state=link

- name: reload nginx
  become: yes
  service: name=nginx state=reloaded
